app = "study-voice-agent"
primary_region = 'sin'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  LANG="C.UTF-8"
